name: Build on macOS

on: push

jobs:
  build-on-macos:
    name: Build on macOS
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Build
        run: ./setup.sh
