name: Build on Ubuntu

on: push

jobs:
  build-on-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Build
        run: ./setup.sh
